In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('adult.csv',header=None)
df.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [3]:
df.columns = ['Age','Workclass','Fnlwgt','Education','Education_num','Marital_status','Occupation','Relation','Race','Sex','Capital_gain','Capital_loss','Hours_per_week','Native_country','Income']
df.head()

Age          Workclass  Fnlwgt   Education  Education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital_status          Occupation        Relation    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital_gain  Capital_loss  Hours_per_week  Native_country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [4]:
df['Workclass'] = df['Workclass'].astype('category')
df['Workclass'] = df['Workclass'].cat.codes
df['Education'] = df['Education'].astype('category')
df['Education'] = df['Education'].cat.codes
df['Marital_status'] = df['Marital_status'].astype('category')
df['Marital_status'] = df['Marital_status'].cat.codes
df['Occupation'] = df['Occupation'].astype('category')
df['Occupation'] = df['Occupation'].cat.codes
df['Relation'] = df['Relation'].astype('category')
df['Relation'] = df['Relation'].cat.codes
df['Race'] = df['Race'].astype('category')
df['Race'] = df['Race'].cat.codes
df['Sex'] = df['Sex'].astype('category')
df['Sex'] = df['Sex'].cat.codes
df['Native_country'] = df['Native_country'].astype('category')
df['Native_country'] = df['Native_country'].cat.codes
df['Income'] = df['Income'].astype('category')
df['Income'] = df['Income'].cat.codes

In [6]:
df.head()

Age  Workclass  Fnlwgt  Education  Education_num  Marital_status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   Occupation  Relation  Race  Sex  Capital_gain  Capital_loss  \
0           1         1     4    1          2174             0   
1           4         0     4    1             0             0   
2           6         1     4    1             0             0   
3           6         0     2    1             0             0   
4          10         5     2    0             0             0   

   Hours_per_week  Native_country  Income  
0              40              39       0  
1              13              39       0  
2              40              39       0  
3              40              39       0  
4              40               5       0

In [5]:
df.shape

(32561, 15)

In [6]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
Education_num     0
Marital_status    0
Occupation        0
Relation          0
Race              0
Sex               0
Capital_gain      0
Capital_loss      0
Hours_per_week    0
Native_country    0
Income            0
dtype: int64

In [7]:
df.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education_num',
       'Marital_status', 'Occupation', 'Relation', 'Race', 'Sex',
       'Capital_gain', 'Capital_loss', 'Hours_per_week', 'Native_country',
       'Income'],
      dtype='object')

In [8]:
r1 = df['Income'].value_counts()
r1

0    24720
1     7841
Name: Income, dtype: int64

In [9]:
df.dtypes

Age               int64
Workclass          int8
Fnlwgt            int64
Education          int8
Education_num     int64
Marital_status     int8
Occupation         int8
Relation           int8
Race               int8
Sex                int8
Capital_gain      int64
Capital_loss      int64
Hours_per_week    int64
Native_country     int8
Income             int8
dtype: object

In [10]:
x = df.iloc[:,:-1]
y = df['Income']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(32561, 14)
(32561,)


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26048, 14)
(6513, 14)
(26048,)
(6513,)


#### Import Models

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [14]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [15]:
def mscore(model):
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))

def gen_matrix(y_test,y_pred):
    cm = confusion_matrix(y_test,y_pred)
    print(cm)
    print(classification_report(y_test,y_pred))
    print('Accuracy Score',accuracy_score(y_test,y_pred))

#### 1) Logistic Regression

In [16]:
m1 = LogisticRegression(max_iter=1000)
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [17]:
mscore(m1)

Training Score 0.7987177518427518
Testing Score 0.8051589129433441


In [18]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[0 0 0 ... 0 0 0]


In [19]:
gen_matrix(y_test,ypred_m1)

[[4801  134]
 [1135  443]]
              precision    recall  f1-score   support

           0       0.81      0.97      0.88      4935
           1       0.77      0.28      0.41      1578

    accuracy                           0.81      6513
   macro avg       0.79      0.63      0.65      6513
weighted avg       0.80      0.81      0.77      6513

Accuracy Score 0.8051589129433441


#### 2) Decision Tree

In [20]:
m2 = DecisionTreeClassifier(criterion= 'gini',min_samples_split=20,max_depth=10)
m2.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=20)

In [21]:
mscore(m2)

Training Score 0.8668995700245701
Testing Score 0.8527560264087211


In [22]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[0 0 1 ... 0 0 0]


In [23]:
gen_matrix(y_test,ypred_m2)

[[4524  411]
 [ 548 1030]]
              precision    recall  f1-score   support

           0       0.89      0.92      0.90      4935
           1       0.71      0.65      0.68      1578

    accuracy                           0.85      6513
   macro avg       0.80      0.78      0.79      6513
weighted avg       0.85      0.85      0.85      6513

Accuracy Score 0.8527560264087211


#### 3) KNN

In [24]:
m3 = KNeighborsClassifier(n_neighbors=5)
m3.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
mscore(m3)

Training Score 0.8354576167076168
Testing Score 0.7741440196530017


In [25]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[0 0 1 ... 0 0 0]


In [26]:
gen_matrix(y_test,ypred_m3)

[[4546  389]
 [1063  515]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86      4935
           1       0.57      0.33      0.41      1578

    accuracy                           0.78      6513
   macro avg       0.69      0.62      0.64      6513
weighted avg       0.75      0.78      0.75      6513

Accuracy Score 0.7770612620912022


#### 4) Support Vector Classifier

In [ ]:
m4 = SVC(kernel='linear',C=1)
m4.fit(x_train,y_train)

In [ ]:
mscore(m4)

In [ ]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

In [ ]:
gen_matrix(y_test,ypred_m4)

#### 5) Random Forest Classifier

In [ ]:
m5 = RandomForestClassifier(criterion = 'gini',min_samples_split = 15,max_depth = 10,random_state = 5)
m5.fit(x_train,y_train)

In [ ]:
mscore(m5)

In [ ]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

In [ ]:
gen_matrix(y_test,ypred_m5)